apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # This defines which pods are going to represented by this service
  # The service becomes a network for either other services or
  # maybe external users to connect to (eg web browser)

  selector:
    release: "0-5"

  ports:
    - name: http
      port: 80
      nodePort: 30080
      targetPort: 80

  type: NodePort